Parameters:
  MFA:
    Type: String
    Default: true
    AllowedValues: [true, false]
  AllowedRegions:
    Type: String
    Default: 'us-east-1'
  MaxSessionDuration:
    Type: Number
    Default: 28800

Conditions:
  HasMFAEnabled: !Equals [true, !Ref MFA]

Resources:
  AssumableAdminRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument: {% include 'policy-statements/assumable-role-policy-document.json'%}
      PermissionsBoundary: !Ref AdminPermissionsBoundary
      Policies:
        - PolicyName: AdminAccess
          PolicyDocument:
            Version: '2008-10-17'
            Statement:
              - Sid: AdminAccess
                Effect: Allow
                Action:
                  - '*'
                Resource:
                  - '*'
      RoleName: AssumableAdminRole
    Type: AWS::IAM::Role

  AssumableReadOnlyRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument: {% include 'policy-statements/assumable-role-policy-document.json'%}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      RoleName: AssumableReadOnlyRole
    Type: AWS::IAM::Role

  AssumableDeveloperRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument: {% include 'policy-statements/assumable-role-policy-document.json'%}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      PermissionsBoundary: !Ref DeveloperPermissionsBoundary
      Policies:
        - PolicyName: CloudFormation
          PolicyDocument:
            Version: '2008-10-17'
            Statement:
              - Sid: AllowDeveloperAccess
                Effect: Allow
                Action:
                  - '*'
                Resource:
                  - "*"
      RoleName: AssumableDeveloperRole
    Type: AWS::IAM::Role

  AssumableCloudFormationDeveloperRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument: {% include 'policy-statements/assumable-role-policy-document.json'%}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      PermissionsBoundary: !Ref DeveloperPermissionsBoundary
      Policies:
        - PolicyName: CloudFormation
          PolicyDocument:
            Version: '2008-10-17'
            Statement:
              - Sid: AllowCloudFormation
                Effect: Allow
                Action:
                  - cloudformation:*
                Resource:
                  - "*"
              - Sid: PassingRoleToCloudFormation
                Effect: Allow
                Action:
                  - iam:PassRole
                  - iam:GetRole
                Resource:
                  - !GetAtt CloudFormationRole.Arn
              - Action:
                  - ecr:DescribeImages
                  - ecr:ListImages
                  - ecr:BatchCheckLayerAvailability
                  - ecr:BatchGetImage
                  - ecr:BatchDeleteImage
                  - ecr:CompleteLayerUpload
                  - ecr:GetAuthorizationToken
                  - ecr:GetDownloadUrlForLayer
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                  - ecr:UploadLayerPart
                  - ecr:BatchDeleteImage
                Effect: Allow
                Resource:
                  - "*"
                Sid: ECRPushAccess
              - Action:
                  - lambda:UpdateFunctionCode
                Effect: Allow
                Resource:
                  - "*"
                Sid: LambdaUpdateFunctionCode
      RoleName: AssumableCloudFormationDeveloperRole
    Type: AWS::IAM::Role

  CloudFormationRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument:
        Statement:
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole
      PermissionsBoundary: !Ref DeveloperPermissionsBoundary
      Policies:
        - PolicyName: CloudFormationRoleAdmin
          PolicyDocument:
            Version: '2008-10-17'
            Statement:
              - Sid: CloudFormationRoleAdmin
                Effect: Allow
                Action:
                  - '*'
                Resource:
                  - '*'
      RoleName: CloudFormationRole
    Type: AWS::IAM::Role


  AssumableSecurityAuditRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument: {% include 'policy-statements/assumable-role-policy-document.json'%}
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/SecurityAudit
      PermissionsBoundary: !Ref DeveloperPermissionsBoundary
      Policies:
        - PolicyName: SecurityAudit
          PolicyDocument:
            Version: '2008-10-17'
            Statement:
              - Action:
                  - support:DescribeTrustedAdvisorChecks
                Effect: Allow
                Resource: "*"
      RoleName: AssumableSecurityAuditRole
    Type: AWS::IAM::Role

  AssumableOperationsRole:
    Properties:
      MaxSessionDuration: !Ref MaxSessionDuration
      AssumeRolePolicyDocument: {% include 'policy-statements/assumable-role-policy-document.json'%}
      PermissionsBoundary: !Ref DeveloperPermissionsBoundary
      Policies:
        - PolicyName: Operations
          PolicyDocument:
            Version: '2008-10-17'
            Statement:
              - Action:
                  - cloudwatch:Describe*
                  - cloudwatch:Get*
                  - cloudwatch:List*
                  - logs:Describe*
                  - logs:Get*
                  - logs:List*
                  - logs:FilterLogEvents
                  - logs:StartQuery
                Effect: Allow
                Resource:
                  - "*"
                Sid: AllowCloudWatchDevopsView
      RoleName: AssumableOperationsRole
    Type: AWS::IAM::Role

