invoke-iteration:
	awsie account-iteration-macro lambda invoke --function-name cf:AccountIterationLambdaFunction: --payload file://event.json /dev/stdout

invoke-list:
	awsie account-iteration-macro lambda invoke --function-name cf:AccountListLambdaFunction: --payload file://event.json /dev/stdout
