AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  CloudTrailLogsRetentionInDays:
    Description: 'The number of days log events are kept in CloudWatch Logs'
    Type: Number
    Default: 90
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
  TrailBucketPrefix:
    Type: String
    Default: 'audit-storage-cloudtrail'
Resources:

  TrailLogGroup:
    Condition: IsGlobalRegion
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: !Ref CloudTrailLogsRetentionInDays
      LogGroupName: /baseline/cloudtrail

  TrailLogGroupRole:
    Condition: IsGlobalRegion
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: CloudTrailAssumeRole
          Effect: Allow
          Principal:
            Service: 'cloudtrail.amazonaws.com'
          Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: 'cloudtrail-policy'
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Sid: AWSCloudTrailCreateLogStream
            Effect: Allow
            Action: 'logs:CreateLogStream'
            Resource: !GetAtt 'TrailLogGroup.Arn'
          - Sid: AWSCloudTrailPutLogEvent
            Effect: Allow
            Action: logs:PutLogEvents
            Resource: !Sub ${TrailLogGroup.Arn}*

  Trail:
    Condition: IsGlobalRegion
    Type: 'AWS::CloudTrail::Trail'
    Properties:
      IncludeGlobalServiceEvents: true
      IsLogging: true
      IsMultiRegionTrail: true
      S3BucketName: !Sub ${TrailBucketPrefix}-${MainAccount}
      CloudWatchLogsLogGroupArn: !GetAtt 'TrailLogGroup.Arn'
      CloudWatchLogsRoleArn: !GetAtt 'TrailLogGroupRole.Arn'
      EnableLogFileValidation: true
