clean-auditing-folders:
	awsie audit-storage s3 rm --recursive s3://cf:CloudTrailBucket:
	awsie audit-storage s3 rm --recursive s3://cf:ConfigBucket:
	awsie audit-storage s3 rm --recursive s3://cf:FlowLogsBucket:
