#!/usr/bin/env bash

SERIAL_NUMBER=""
TOKEN_CODE=""
MFA=""
PROFILE=""

while getopts "ms:t:d:p:" opt; do
    case "$opt" in
        t) TOKEN_CODE="--token-code $OPTARG" ;;
        s) SERIAL_NUMBER="--serial-number $OPTARG" ;;
        d) MAX_DURATION="--duration-seconds $(expr $OPTARG \* 3600)" ;;
        m) MFA="TRUE" ;;
        p) PROFILE="--profile $OPTARG"
    esac
done
shift $(($OPTIND-1))

read -r ACCOUNT USERNAME <<<$(aws sts get-caller-identity --query "[Account, Arn]" --output text $PROFILE | sed 's/arn.*\///g')

if [[ ! -z "$MFA" && -z "$SERIAL_NUMBER" ]]
then
  MFA_DEVICE=arn:aws:iam::$ACCOUNT:mfa/$USERNAME
  SERIAL_NUMBER="--serial-number $MFA_DEVICE"
fi

if [[ ! -z "$SERIAL_NUMBER" && -z "$TOKEN_CODE" ]]
then
  read -p "MFA TOKEN: " TOKEN
  TOKEN_CODE="--token-code $TOKEN"
fi

aws sts get-session-token ${SERIAL_NUMBER:-} ${TOKEN_CODE:-} ${MAX_DURATION:-} --output json $PROFILE | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=" + .AccessKeyId + " AWS_SECRET_ACCESS_KEY=" + .SecretAccessKey + " AWS_SESSION_TOKEN=\"" + .SessionToken + "\" AWS_TOKEN_EXPIRATION=" + .Expiration'