#!/usr/bin/env bash

set -euo pipefail

# Based on https://gist.github.com/jokeru/e4a25bbd95080cfd00edf1fa67b06996

echo "Deleting Default VPCs in all Accounts"

for region in $(aws ec2 describe-regions --query Regions[].RegionName --output text); do

  echo "----- ${region} ----------"

  export AWS_DEFAULT_REGION=${region}

  # get default vpc
  vpcs=$(aws ec2 describe-vpcs --filter Name=isDefault,Values=true --query "Vpcs[].VpcId" --output text)

  if [[ -z "${vpcs}" ]]; then
    echo "No default VPC Found"
  else
    for vpc in ${vpcs}; do

      # get internet gateway
      igws=$(aws ec2 --region ${region} describe-internet-gateways --filter Name=attachment.vpc-id,Values=${vpc} --query "InternetGateways[].InternetGatewayId" --output text)
      for igw in ${igws}; do
        echo "IGW:    ${igw}"
        aws ec2 detach-internet-gateway --internet-gateway-id ${igw} --vpc-id ${vpc}
        aws ec2 delete-internet-gateway --internet-gateway-id ${igw}
      done

      # get subnets
      subnets=$(aws ec2 --region ${region} describe-subnets --filters Name=vpc-id,Values=${vpc} --query "Subnets[].SubnetId" --output text)
      for subnet in ${subnets}; do
        echo "Subnet: ${subnet}"
        aws ec2 --region ${region} delete-subnet --subnet-id ${subnet}
      done

      # https://docs.aws.amazon.com/cli/latest/reference/ec2/delete-vpc.html
      # - You can't delete the main route table
      # - You can't delete the default network acl
      # - You can't delete the default security group

      # delete default vpc
      echo "VPC:    ${vpc}"
      aws ec2 --region ${region} delete-vpc --vpc-id ${vpc}
    done
  fi
done
